import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Header from "@/components/Header";
// import Footer from "@/components/Footer";
import DynamicPixel from "@/components/DynamicPixel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Include legacy CSS to match existing PHP UI */}
        <link
          rel="stylesheet"
          href="/assets/css/bootstrap.min.css"
        />
        <link
          rel="stylesheet"
          href="/assets/css/custom.css"
        />
        <link href="https://fonts.googleapis.com/css2?family=roboto&display=swap" rel="stylesheet" />
        <DynamicPixel />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
